"""
URL configuration for ciet_main project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
<<<<<<< HEAD
    path('', include('Initiatives.MajorProjects.urls')),
    path('', include('About.People.urls')),
    path('', include('Activities.ICT_awards.urls')),
    path('', include('About.About_us.urls')),
    path('', include('About.Advisory_board.urls')),
    path('', include('Activities.Calender.urls')),
    path('', include('Departments.dept_ICT_Training.urls')),
    path('', include('Initiatives.PAB_Projects.urls')),
    path('', include('Initiatives.PAC_Projects.urls')),
    path('', include('Activities.Webinars.urls')),
    path('', include('Activities.Conference.urls')),
    path('', include('Activities.Counselling_Services.urls')),
    path('', include('Activities.Live_Classrooms.urls')),
    path('', include('Activities.NISHTHA.urls')),
    path('', include('Activities.SRG.urls')),
    path('', include('Departments.Media_Production_Division.urls')),
    path('', include('Departments.Planning_Research_Division.urls')),
    path('', include('Departments.Engineering_division.urls')),
    path('', include('More.RTI.urls')),
    path('', include('More.Announcements.urls')),
    path('', include('More.Contact.urls')),
    path('', include('Resources.Cyber_Safety.urls')),
    path('', include('Resources.eContent_Guidelines.urls')),
    path('', include('Resources.Catalogue.urls')),
    path('', include('Resources.Brochure_ICT_Initiatives.urls')),
    path('', include('Resources.Journals.urls')),
    path('', include('Resources.Newsletter.urls')),
    path('', include('Resources.eContent_Evaluation.urls')),
    path('', include('Resources.Reports.urls')),
    path('', include('Resources.UNESCO.urls')),
    path('', include('Resources.Learning_Objects.urls')),
    path('', include('Resources.NCERT_Initiatives.urls')),
    path('', include('Resources.Audio_Books.urls')),
    path('', include('Activities.TV_Channels.urls')),
    path('', include('Activities.Workshop_Training.urls')),
    path('', include('Resources.Alternative_Academic_Calender.urls')),
    path('', include('screen_reader_access.urls')),
    path('', include('Departments.administration_accounts.urls')),
    path('', include('Library.urls')),
    path('', include('cyber_jaagrookta.urls')),
    path('', include('digital_creativity.urls')),
    path('', include('pmevidya.urls')),
    path('', include('epathshala.urls')),
    path('', include('diksha.urls')),
    path('', include('moocs_on_swayam.urls')),
    path('', include('nishtha.urls')),
    path('', include('ncf_tech.urls')),
    path('', include('ict_curriculum.urls')),
    path('', include('school_curriculum.urls')),
    path('', include('barkhaa.urls')),
    path('', include('special_econtent.urls')),
    path('', include('priya_warrior.urls')),
    path('', include('teachers_support.urls')),
    path('', include('ar_vr.urls')),
    path('', include('prashast.urls')),
    path('', include('evidya_dth.urls')),
    path('', include('bharatonthemoon.urls')),
    path('', include('ejaadui_pitara.urls')),
    path('', include('translation_cell.urls')),
    path('', include('summer_camp.urls')),
    path('', include('privacy_policy.urls')),
=======
    path('major_projects/', include('Initiatives.MajorProjects.urls')),
    path('people/', include('About.People.urls')),
    path('Activities/', include('Activities.ICT_awards.urls')),
    path('about_us/', include('About.About_us.urls')),
    path('advisory_board/', include('About.Advisory_board.urls')),
    path('calender/', include('Activities.Calender.urls')),
    path('dept_ict_training/', include('Departments.dept_ICT_Training.urls')),
    path('pab_projects/', include('Initiatives.PAB_Projects.urls')),
    path('pac_projects/', include('Initiatives.PAC_Projects.urls')),
    path('webinars/', include('Activities.Webinars.urls')),
    path('conference/', include('Activities.Conference.urls')),
    path('counselling_services/', include('Activities.Counselling_Services.urls')),
    path('live_classrooms/', include('Activities.Live_Classrooms.urls')),
    path('Activities_nishtha/', include('Activities.NISHTHA.urls')),
    path('srg/', include('Activities.SRG.urls')),
    path('mpd/', include('Departments.Media_Production_Division.urls')),
    path('prd/', include('Departments.Planning_Research_Division.urls')),
    path('ed/', include('Departments.Engineering_division.urls')),
    path('rti/', include('More.RTI.urls')),
    path('announcements/', include('More.Announcements.urls')),
    path('contact/', include('More.Contact.urls')),
    path('cyber_safety_security/', include('Resources.Cyber_Safety.urls')),
    path('econtent_guidelines/', include('Resources.eContent_Guidelines.urls')),
    path('catalogue/', include('Resources.Catalogue.urls')),
    path('brochure/', include('Resources.Brochure_ICT_Initiatives.urls')),
    path('journals/', include('Resources.Journals.urls')),
    path('Newsletters/', include('Resources.Newsletter.urls')),
    path('econtent_eval/', include('Resources.eContent_Evaluation.urls')),
    path('reports/', include('Resources.Reports.urls')),
    path('unesco/', include('Resources.UNESCO.urls')),
    path('learning_objects/', include('Resources.Learning_Objects.urls')),
    path('ncert_initiatives/', include('Resources.NCERT_Initiatives.urls')),
    path('audio_books/', include('Resources.Audio_Books.urls')),
    path('tv_channels/', include('Activities.TV_Channels.urls')),
    path('workshop_training/', include('Activities.Workshop_Training.urls')),
    path('alternative_academic_calender/', include('Resources.Alternative_Academic_Calender.urls')),
    path('screen_reader_access/', include('screen_reader_access.urls')),
    path('administration_accounts/', include('Departments.administration_accounts.urls')),
    path('library/', include('Library.urls')),
    path('cyber_jaagrookta/', include('cyber_jaagrookta.urls')),
    path('digital_creativity/', include('digital_creativity.urls')),
    path('pm_evidya/', include('pmevidya.urls')),
    path('epathshala/', include('epathshala.urls')),
    path('diksha/', include('diksha.urls')),
    path('moocs_on_swayam/', include('moocs_on_swayam.urls')),
    path('nishtha/', include('nishtha.urls')),
    path('ncf_tech/', include('ncf_tech.urls')),
    path('ict_curriculum/', include('ict_curriculum.urls')),
    path('school_curriculum/', include('school_curriculum.urls')),
    path('barkhaa/', include('barkhaa.urls')),
    path('special_econtent/', include('special_econtent.urls')),
    path('priya_warrior/', include('priya_warrior.urls')),
    path('teachers_support/', include('teachers_support.urls')),
    path('ar_vr/', include('ar_vr.urls')),
    path('prashast/', include('prashast.urls')),
    path('evidya_dth/', include('evidya_dth.urls')),
    path('bharatonthemoon/', include('bharatonthemoon.urls')),
    path('ejaadui_pitara/', include('ejaadui_pitara.urls')),
    path('translation_cell/', include('translation_cell.urls')),

    path('summer_camp/', include('summer_camp.urls')),

    path('privacy_policy/', include('privacy_policy.urls')),

    #path('conference_video/', include('conference_video.urls')),
>>>>>>> 0cb936e6d9195784d6a747932c31a82c2b5d90ee
    path('', include('conference_video.urls')),
    path('', include('comics.urls')),
<<<<<<< HEAD
    path('', include('daisy_books.urls')),
    path('', include('eContent_comp.urls')),
    path('', include('ec23.urls')),
    path('', include('finaleventec23.urls')),
    path('', include('festivalec23.urls')),
    path('', include('registrationec23.urls')),
    path('', include('entriesec23.urls')),
    path('', include('galleryec23.urls')),
=======


    path('eContent_comp/', include('eContent_comp.urls')),
    path('ec23/', include('ec23.urls')),
    path('finaleventec23/', include('finaleventec23.urls')),
    path('festivalec23/', include('festivalec23.urls')),
    path('registrationec23/', include('registrationec23.urls')),
    path('entriesec23/', include('entriesec23.urls')),
    path('galleryec23/', include('galleryec23.urls')),

    path('', include('online_course.urls')),
>>>>>>> 0cb936e6d9195784d6a747932c31a82c2b5d90ee
]
